Repository grafeas/grafeas, pull requests merged in 2021-11, with the labels that each got.

#512 Add in the proto changes required for adding cvss v3 info to Occs.
  proto/v1/vulnerability.proto
Labels: size/S

#515 Use backticks for strings and place the comments on the line above.
  proto/v1/compliance.proto
  proto/v1/intoto_statement.proto
Labels: size/S

#514 Add grafeas-rds to list of backends.
  README.md
Labels: size/XS

#513 introduce a common CVSS proto message which can be supported for both v2 & v3
  proto/v1beta1/cvss.proto
  proto/v1beta1/cvss_go_proto/cvss.pb.go
  proto/v1beta1/grafeas_go_proto/grafeas_grpc.pb.go
  proto/v1beta1/project_go_proto/project_grpc.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/vulnerability.proto
  proto/v1beta1/vulnerability_go_proto/vulnerability.pb.go
Labels: size/XXL

#518 Add CVSS proto to v1 and modify the proto in Occurrences to use this one (this is ok since we have not yet persisted this data and have not released a new version yet).
  proto/v1/cvss.proto
  proto/v1/vulnerability.proto
Labels: size/M
