Repository grafeas/grafeas, pull requests merged in 2021-12, with the labels that each got.

#521 Add archive time field to discovery occurrence
  proto/v1/discovery.proto
Labels: size/XS

#523 upgrade to grpc-gateway/v2@v2.7.0
  go.mod
  go.sum
  proto/v1beta1/grafeas_go_proto/grafeas_grpc.pb.go
  proto/v1beta1/project_go_proto/project_grpc.pb.go
Labels: size/XS

#524 Move the severity enum into its own proto
  proto/v1/compliance.proto
  proto/v1/generate.go
  proto/v1/severity.proto
  proto/v1/vulnerability.proto
Labels: size/M

#525 Update tools/grpc-gateway@v2.7.0
  cel/syntax.pb.go
  proto/v1alpha1/grafeas.proto
  proto/v1alpha1/swagger/grafeas.swagger.json
  proto/v1beta1/attestation_go_proto/attestation.pb.go
  proto/v1beta1/build_go_proto/build.pb.go
  proto/v1beta1/common_go_proto/common.pb.go
  proto/v1beta1/cvss_go_proto/cvss.pb.go
  proto/v1beta1/deployment_go_proto/deployment.pb.go
  proto/v1beta1/discovery_go_proto/discovery.pb.go
  proto/v1beta1/grafeas_go_proto/grafeas.pb.go
  proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go
  proto/v1beta1/image_go_proto/image.pb.go
  proto/v1beta1/intoto_go_proto/intoto.pb.go
  proto/v1beta1/package_go_proto/package.pb.go
  proto/v1beta1/project_go_proto/project.pb.go
  proto/v1beta1/project_go_proto/project.pb.gw.go
  proto/v1beta1/provenance_go_proto/provenance.pb.go
  proto/v1beta1/source_go_proto/source.pb.go
  proto/v1beta1/spdx_go_proto/spdx.pb.go
  proto/v1beta1/swagger/attestation.swagger.json
  proto/v1beta1/swagger/build.swagger.json
  proto/v1beta1/swagger/common.swagger.json
  proto/v1beta1/swagger/cvss.swagger.json
  proto/v1beta1/swagger/deployment.swagger.json
  proto/v1beta1/swagger/discovery.swagger.json
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/image.swagger.json
  proto/v1beta1/swagger/intoto.swagger.json
  proto/v1beta1/swagger/package.swagger.json
  proto/v1beta1/swagger/project.swagger.json
  proto/v1beta1/swagger/provenance.swagger.json
  proto/v1beta1/swagger/source.swagger.json
  proto/v1beta1/swagger/spdx.swagger.json
  proto/v1beta1/swagger/vulnerability.swagger.json
  proto/v1beta1/vulnerability_go_proto/vulnerability.pb.go
  tools/go.mod
  tools/go.sum
Labels: size/XL

#526 add java_outer_classname to intoto to avoid java client generation failures
  proto/v1/intoto_provenance.proto
Labels: size/XS

#527 add cwe field to vulnerability message in v1beta1
  proto/v1beta1/vulnerability.proto
  proto/v1beta1/vulnerability_go_proto/vulnerability.pb.go
Labels: size/L

#529 Spelling
  CHANGELOG.md
  RELEASING.md
  cel/syntax.pb.go
  docs/json_examples/note_deployment.json
  docs/json_examples/occurrence_deployment.json
  docs/postman/Grafeas API.postman_collection.json
  go/filtering/README.md
  go/filtering/common/errors_test.go
  go/filtering/common/source_test.go
  go/filtering/parser/parser.go
  go/filtering/parser/testdata/README.md
  go/v1beta1/config.yaml
  go/v1beta1/example/client/client.go
  go/v1beta1/storage/pgsqlstore.go
  go/v1beta1/storage/pgsqlstore_test.go
  go/v1beta1/storage/storage.go
  grafeas-charts/README.md
  proto/v1alpha1/grafeas.proto
  proto/v1alpha1/swagger/grafeas.swagger.json
  proto/v1beta1/attestation.proto
  proto/v1beta1/attestation_go_proto/attestation.pb.go
  proto/v1beta1/spdx.proto
  proto/v1beta1/spdx_go_proto/spdx.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
Labels: size/M

#528 add dsse envelope proto message to v1beta1 APIs
  proto/v1beta1/common.proto
  proto/v1beta1/common_go_proto/common.pb.go
  proto/v1beta1/grafeas.proto
  proto/v1beta1/grafeas_go_proto/grafeas.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
Labels: size/XXL

#530 release v0.2.0
  CHANGELOG.md
  grafeas-charts/Chart.yaml
  grafeas-charts/values.yaml
Labels: size/S
