Repository grafeas/grafeas, pull requests merged in 2021-08, with the labels that each got.

#497 Make provenance optional
  go/v1/api/validators/build/build.go
  go/v1/api/validators/build/build_test.go
Labels: size/S

#499 Change intoto provenance environment and arguments to be of Any type.
  proto/v1/intoto_provenance.proto
Labels: size/XS

#501 Add SBOM protos
  proto/v1beta1/generate.go
  proto/v1beta1/grafeas.proto
  proto/v1beta1/grafeas_go_proto/grafeas.pb.go
  proto/v1beta1/spdx_document.proto
  proto/v1beta1/spdx_document_go_proto/spdx_document.pb.go
  proto/v1beta1/spdx_file.proto
  proto/v1beta1/spdx_file_go_proto/spdx_file.pb.go
  proto/v1beta1/spdx_package.proto
  proto/v1beta1/spdx_package_go_proto/spdx_package.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/spdx_document.swagger.json
  proto/v1beta1/swagger/spdx_file.swagger.json
  proto/v1beta1/swagger/spdx_package.swagger.json
Labels: size/XXL
