Repository grafeas/grafeas, pull requests merged in 2022-06, with the labels that each got.

#552 Change the type of digest_value to bytes to store raw digests instead of encoded values
  proto/v1/common.proto
  proto/v1/grafeas_go_proto/common.pb.go
  proto/v1/swagger/grafeas.swagger.json
  proto/v1beta1/common.proto
  proto/v1beta1/common_go_proto/common.pb.go
  proto/v1beta1/grafeas_go_proto/grafeas_grpc.pb.go
  proto/v1beta1/project_go_proto/project_grpc.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
Labels: size/M

#555 Upgrade to Go 1.18
  .circleci/config.yml
  Dockerfile
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: size/XS

#554 Add SLSA 0.2 converter
  go.mod
  go.sum
  go/utils/intoto/slsa_zero_two_converter.go
  go/utils/intoto/slsa_zero_two_converter_test.go
  go/utils/intoto/testdata/slsa02Provenance.json
Labels: size/L

#556 Update in-toto-golang version
  go.mod
  go.sum
Labels: size/XS
