Repository grafeas/grafeas, pull requests merged in 2022-04, with the labels that each got.

#541 Adding a way to indicate the location at which a package was found on PackageIssue
  proto/v1/common.proto
  proto/v1/vulnerability.proto
Labels: size/S

#543 fix slsa_provenance outer calss name
  proto/v1/slsa_provenance.proto
Labels: size/XS

#544 Regenerate for `v1` API and add Swagger for `v1`
  proto/v1/generate.go
  proto/v1/grafeas_go_proto/common.pb.go
  proto/v1/grafeas_go_proto/slsa_provenance.pb.go
  proto/v1/grafeas_go_proto/vulnerability.pb.go
  proto/v1/swagger/grafeas.swagger.json
Labels: size/XXL

#545 Expand PackageNote and PackageProto to support language packages
  proto/v1/common.proto
  proto/v1/grafeas_go_proto/common.pb.go
  proto/v1/grafeas_go_proto/package.pb.go
  proto/v1/package.proto
  proto/v1/swagger/grafeas.swagger.json
Labels: size/XL
