Repository grafeas/grafeas, pull requests merged in 2022-05, with the labels that each got.

#546 Expand v1beta1 Package protos to support language packages.
  proto/v1/dsse_attestation.proto
  proto/v1/grafeas_go_proto/package.pb.go
  proto/v1/package.proto
  proto/v1/swagger/grafeas.swagger.json
  proto/v1beta1/common.proto
  proto/v1beta1/common_go_proto/common.pb.go
  proto/v1beta1/cvss.proto
  proto/v1beta1/cvss_go_proto/cvss.pb.go
  proto/v1beta1/package.proto
  proto/v1beta1/package_go_proto/package.pb.go
  proto/v1beta1/spdx.proto
  proto/v1beta1/spdx_go_proto/spdx.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
Labels: size/XXL

#547 Make package name a required field in the Package occurrence.
  proto/v1/grafeas_go_proto/package.pb.go
  proto/v1/package.proto
  proto/v1/swagger/grafeas.swagger.json
  proto/v1beta1/package.proto
  proto/v1beta1/package_go_proto/package.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
Labels: size/L

#549 Fix go1.18 vet error: (*testing.common).Error call has possible formatting directive.
  go/filtering/common/source_test.go
Labels: size/XS

#551 Rename 0_2 to ZeroTwo, to be in line with aip 140.
  proto/v1/generate.go
  proto/v1/grafeas_go_proto/intoto_statement.pb.go
  proto/v1/grafeas_go_proto/slsa_provenance_0_2.pb.go
  proto/v1/grafeas_go_proto/slsa_provenance_zero_two.pb.go
  proto/v1/intoto_statement.proto
  proto/v1/slsa_provenance_zero_two.proto
  proto/v1/swagger/grafeas.swagger.json
Labels: size/XXL
