Repository grafeas/grafeas, pull requests merged in 2023-03, with the labels that each got.

#575 Remove remediation_uri field, change publisher.context to publisher_namespace.
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
  proto/v1beta1/vex.proto
  proto/v1beta1/vex_go_proto/vex.pb.go
Labels: size/S

#576 Move vex to v1 api from v1beta1
  proto/v1/common.proto
  proto/v1/generate.go
  proto/v1/grafeas.proto
  proto/v1/grafeas_go_proto/common.pb.go
  proto/v1/grafeas_go_proto/grafeas.pb.go
  proto/v1/grafeas_go_proto/vex.pb.go
  proto/v1/grafeas_go_proto/vulnerability.pb.go
  proto/v1/swagger/grafeas.swagger.json
  proto/v1/vex.proto
  proto/v1/vulnerability.proto
Labels: size/L

#578 Add SBOM Reference to v1b1
  proto/v1beta1/generate.go
  proto/v1beta1/grafeas.proto
  proto/v1beta1/grafeas_go_proto/grafeas.pb.go
  proto/v1beta1/intoto.proto
  proto/v1beta1/intoto_go_proto/intoto.pb.go
  proto/v1beta1/sbom.proto
  proto/v1beta1/sbom_go_proto/sbom.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
Labels: size/L

#579 Move the sbom reference into the oneof
  proto/v1beta1/grafeas.proto
  proto/v1beta1/intoto.proto
  proto/v1beta1/sbom.proto
Labels: size/M

#580 Add SBOM Reference kind to v1b1
  proto/v1beta1/common.proto
Labels: size/XS

#565 Use ANTLR v4
  go.mod
  go.sum
  go/filtering/parser/gen/FilterExpression.interp
  go/filtering/parser/gen/FilterExpressionLexer.interp
  go/filtering/parser/gen/filterexpression_base_visitor.go
  go/filtering/parser/gen/filterexpression_lexer.go
  go/filtering/parser/gen/filterexpression_parser.go
  go/filtering/parser/gen/filterexpression_visitor.go
  go/filtering/parser/parser.go
Labels: size/S

#582 add enum for grafeas v1 cvss to support both cvss v2 and v3
  proto/v1/cvss.proto
  proto/v1/grafeas_go_proto/cvss.pb.go
  proto/v1/swagger/grafeas.swagger.json
  proto/v1beta1/common_go_proto/common.pb.go
  proto/v1beta1/grafeas_go_proto/grafeas.pb.go
  proto/v1beta1/intoto_go_proto/intoto.pb.go
  proto/v1beta1/sbom_go_proto/sbom.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
Labels: size/L
