Repository grafeas/grafeas, pull requests merged in 2023-02, with the labels that each got.

#567 #566 Enable Grafeas to store and retrieve Vex information
  cel/syntax.pb.go
  proto/v1beta1/attestation_go_proto/attestation.pb.go
  proto/v1beta1/common.proto
  proto/v1beta1/common_go_proto/common.pb.go
  proto/v1beta1/generate.go
  proto/v1beta1/grafeas.proto
  proto/v1beta1/grafeas_go_proto/grafeas.pb.go
  proto/v1beta1/intoto_go_proto/intoto.pb.go
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
  proto/v1beta1/vex.proto
  proto/v1beta1/vex_go_proto/vex.pb.go
  proto/v1beta1/vulnerability.proto
  proto/v1beta1/vulnerability_go_proto/vulnerability.pb.go
Labels: size/XL

#568 added cvss_v2 into notes and occurrences for both v1 and v1beta1.
  proto/v1/grafeas_go_proto/vulnerability.pb.go
  proto/v1/swagger/grafeas.swagger.json
  proto/v1/vulnerability.proto
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
  proto/v1beta1/vulnerability.proto
  proto/v1beta1/vulnerability_go_proto/vulnerability.pb.go
Labels: size/M

#570 Add justification type and justification message, simplify Threats
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
  proto/v1beta1/vex.proto
  proto/v1beta1/vex_go_proto/vex.pb.go
  proto/v1beta1/vulnerability.proto
  proto/v1beta1/vulnerability_go_proto/vulnerability.pb.go
Labels: size/L

#572 Minor change to the JustificationType enums.
  proto/v1beta1/swagger/grafeas.swagger.json
  proto/v1beta1/swagger/merged/grafeas.swagger.json
  proto/v1beta1/vex.proto
  proto/v1beta1/vex_go_proto/vex.pb.go
Labels: size/M
